global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'your-email@gmail.com'
  smtp_auth_username: 'your-email@gmail.com'
  smtp_auth_password: 'your-app-password'
  smtp_require_tls: true

route:
  receiver: 'email-notifications'
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h

receivers:
- name: 'email-notifications'
  email_configs:
  - to: 'recipient@example.com'
    send_resolved: true
    subject: '{{ .CommonAnnotations.summary }}'
    html: '{{ .CommonAnnotations.description }}'