global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'airflow'
    static_configs:
      - targets: ['host.docker.internal:8793']

  - job_name: 'spark'
    static_configs:
      - targets: ['host.docker.internal:4040']